# Generated by Django 5.0.6 on 2024-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0003_remove_order_books_order_available_order_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordered Product Quantity'),
        ),
    ]
