# Generated by Django 5.0.6 on 2024-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0004_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateField(auto_now=True, null=True, verbose_name='Ordered On'),
        ),
    ]
