# Generated by Django 5.0.6 on 2024-05-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0006_alter_order_delivered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='available',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=100000, verbose_name='Customer Email'),
        ),
    ]
