# Generated by Django 5.0.6 on 2024-05-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0007_remove_order_available_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=10000000, verbose_name='Paypal Order Id'),
        ),
    ]
