# Generated by Django 5.0.6 on 2024-05-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0008_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chapter Number'),
        ),
    ]
